[build]
target              = "index.html"
bin                 = "explore"
features            = ["client"]
no_default_features = true

[watch]
watch               = ["./src/client"]

[serve]
port                = 3000
open                = false
