[package]
name           = "rbp-nlhe"
version        = "1.0.0"
edition        = "2024"
rust-version   = "1.90"
authors        = ["Kelechi Ukah <ukahkelechi@gmail.com>"]
description    = "No-Limit Hold'em MCCFR solver with Pluribus-inspired abstraction"
license        = "MIT"
repository     = "https://github.com/krukah/robopoker"
keywords       = ["poker", "nlhe", "holdem", "mccfr", "pluribus"]
categories     = ["game-development", "algorithms"]

[features]
default        = []
database       = ["tokio-postgres", "const_format", "async-trait", "rbp-database"]
server         = ["rbp-mccfr/server"]

[dependencies]
rbp-core       = { version = "1.0", path = "../util"      }
rbp-cards      = { version = "1.0", path = "../cards"     }
rbp-gameplay   = { version = "1.0", path = "../gameplay"  }
rbp-transport  = { version = "1.0", path = "../transport" }
rbp-mccfr      = { version = "1.0", path = "../mccfr"     }
rbp-database   = { version = "1.0", path = "../database", optional = true }
log            = "0.4"
rand           = { version = "0.9.1", features = ["small_rng"] }
anyhow         = "1.0"
tokio-postgres = { version = "0.7", optional = true }
const_format   = { version = "0.2", optional = true }
async-trait    = { version = "0.1", optional = true }
