[package]
name            = "rbp-hosting"
version         = "0.1.0"
edition         = "2024"
rust-version    = "1.90"
authors         = ["Kelechi Ukah <ukahkelechi@gmail.com>"]
description     = "WebSocket game hosting infrastructure"
license         = "MIT"

[dependencies]
rbp-core        = { path = "../rbp-core"     }
rbp-auth        = { path = "../rbp-auth"     }
rbp-gameroom    = { path = "../rbp-gameroom" }
rbp-gameplay    = { path = "../rbp-gameplay" }
rbp-players     = { path = "../rbp-players"  }
rbp-records     = { path = "../rbp-records"  }
tokio-postgres  = "0.7"
tokio           = { version = "1", features = ["sync", "rt"] }
actix-web       = "4"
actix-ws        = "0.3"
async-trait     = "0.1"
uuid            = "1"
futures         = "0.3"
serde_json      = "1"
log             = "0.4"
anyhow          = "1"
