[package]
name           = "rbp-nlhe"
version        = "0.1.0"
edition        = "2024"
rust-version   = "1.90"
authors        = ["Kelechi Ukah <ukahkelechi@gmail.com>"]
description    = "No-Limit Hold'em specific CFR implementation"
license        = "MIT"

[features]
default        = []
database       = ["tokio-postgres", "const_format", "async-trait", "rbp-pg"]
server         = ["rbp-mccfr/server"]

[dependencies]
rbp-core       = { path = "../rbp-core" }
rbp-cards      = { path = "../rbp-cards" }
rbp-gameplay   = { path = "../rbp-gameplay" }
rbp-transport  = { path = "../rbp-transport" }
rbp-mccfr      = { path = "../rbp-mccfr" }
rbp-dto        = { path = "../rbp-dto" }
rbp-pg         = { path = "../rbp-pg", optional = true }
log            = "0.4"
rand           = { version = "0.9.1", features = ["small_rng"] }
anyhow         = "1.0"
tokio-postgres = { version = "0.7", optional = true }
const_format   = { version = "0.2", optional = true }
async-trait    = { version = "0.1", optional = true }
