[package]
name            = "rbp-players"
version         = "0.1.0"
edition         = "2024"
rust-version    = "1.90"
authors         = ["Kelechi Ukah <ukahkelechi@gmail.com>"]
description     = "Player implementations for poker game room"
license         = "MIT"

[features]
default         = []
database        = ["rbp-pg", "tokio-postgres"]
cli             = ["dialoguer"]

[dependencies]
rbp-core        = { path = "../rbp-core"      }
rbp-gameplay    = { path = "../rbp-gameplay"  }
rbp-gameroom    = { path = "../rbp-gameroom"  }
rbp-mccfr       = { path = "../rbp-mccfr"     }
rbp-nlhe        = { path = "../rbp-nlhe"      }
rbp-transport   = { path = "../rbp-transport" }
rbp-pg          = { path = "../rbp-pg", optional = true      }
tokio-postgres  = { version = "0.7",   optional = true       }
dialoguer       = { version = "0.11",  optional = true       }
async-trait     = "0.1"
rand            = { version = "0.9.1", features = ["small_rng"] }
